---
# https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_replication_module.html
- name: "Install Grafana utils"
  apt:
    pkg:
      - apt-transport-https
      - libfontconfig1
      - software-properties-common
      - wget
    update_cache: yes

# https://docs.ansible.com/ansible/2.9/modules/user_module.html
- name: "Create grafana User"
  user:
    name: grafana
    comment: grafana user
    create_home: no

- name: "Download and Unzip Grafana Package"
  shell: |
    cd /tmp/

    wget https://dl.grafana.com/oss/release/grafana_7.3.4_amd64.deb

- name: "Install Grafana dpkg"
  command: dpkg -i /tmp/grafana_7.3.4_amd64.deb

- name: "Restart grafana Service"
  service:
    name: grafana-server
    state: restarted