---
- name: "Wordpress Requirements Installation"
  apt:
    pkg:
      - nginx
      - unzip
      - php7.4-zip
      - php-imagick
      - php7.4-curl
      - php7.4-fpm
      - php7.4-mbstring
      - php7.4-cli
      - php7.4-bcmath
      - php7.4-xml
      - php7.4-mysql
      - php7.4-common
      - php7.4-gd
      - php7.4-json
    update_cache: yes
    # check if php was installed correctly
    # ls -l /run/php/php7.4-fpm.sock

- name: "NGINX Vhost Configuration"
  template:
    src: vhost.nginx.conf.j2 # templates extension
    dest: /etc/nginx/sites-enabled/default

- name: "Download and Unzip Wordpress Package"
  ansible.builtin.unarchive:
    src: https://wordpress.org/latest.zip
    dest: /var/www/html
    remote_src: yes

- name: "Update the wp-config File"
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php

- name: "Change Permissions for /var/www/html/wordpress"
  ansible.builtin.file:
    path: /var/www/html/wordpress
    owner: www-data
    group: www-data
    mode: '0755'

- name: "Restart NGINX"
  service:
    name: nginx
    state: restarted
