---
# https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_replication_module.html
- name: "Install MySQL utils"
  apt:
    pkg:
      - mysql-client
      - python3-mysqldb
      - libmysqlclient-dev
      - python3-pymysql
    update_cache: yes

- name: "MySQL setup configuration template"
  template:
    src: setup-mysql.sh.j2
    dest: /tmp/setup-mysql.sh
    mode: 0775

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
- name: "Setup MySQL for Wordpress using shell script"
  ansible.builtin.command: /tmp/setup-mysql.sh
